name: Prepare R package
on: workflow_dispatch

jobs:
  generate:
    name: Prepare in Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 'devel'
    - name: Clone
      run: |
        git clone https://github.com/duckdb/duckdb.git
    - name: rconfigure
      run: |
        cd duckdb/tools/rpkg
        python rconfigure.py
        sed -i "s/'Windows'/platform.system()/g" rconfigure.py
        sed -i "s/'Makevars'/'Makevars.win'/g" rconfigure.py
        python rconfigure.py
    - name: Build source package
      run: |
        R CMD build duckdb/tools/rpkg
    - name: Extract package
      run: |
        tar -xf duckdb*.tar.gz -C main
    - name: Commit and push
      run: |
        cd main
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add .
        git commit -m "Package update"
        git push
        
